// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASJfoztUbx41z76tKU0ItknYoQUKVbRGc',
    appId: '1:131092586115:web:f76973b919d576c9c005b6',
    messagingSenderId: '131092586115',
    projectId: 'myapp-flutter-project2',
    authDomain: 'myapp-flutter-project2.firebaseapp.com',
    storageBucket: 'myapp-flutter-project2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzSIKfEZ_NgeLsJhy-lOn_OcaZMs5A3zE',
    appId: '1:131092586115:android:40568081461ec761c005b6',
    messagingSenderId: '131092586115',
    projectId: 'myapp-flutter-project2',
    storageBucket: 'myapp-flutter-project2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByy5HXl9f9Bc74xejdw4XT81udDM6ehV4',
    appId: '1:131092586115:ios:313bc897fed0b05fc005b6',
    messagingSenderId: '131092586115',
    projectId: 'myapp-flutter-project2',
    storageBucket: 'myapp-flutter-project2.appspot.com',
    iosBundleId: 'com.example.myapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByy5HXl9f9Bc74xejdw4XT81udDM6ehV4',
    appId: '1:131092586115:ios:10077c6ea299e115c005b6',
    messagingSenderId: '131092586115',
    projectId: 'myapp-flutter-project2',
    storageBucket: 'myapp-flutter-project2.appspot.com',
    iosBundleId: 'com.example.myapp2.RunnerTests',
  );
}
